# Generated by Django 3.1.11 on 2021-06-17 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_train', models.CharField(max_length=30, unique=True, verbose_name='Номер поезда')),
                ('travel_time', models.SmallIntegerField(verbose_name='Время в пути')),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_from', to='cities.city')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_to', to='cities.city')),
            ],
        ),
    ]
