# Generated by Django 3.1.11 on 2021-06-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='city_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_from_set', to='cities.city'),
        ),
        migrations.AlterField(
            model_name='train',
            name='city_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_to_set', to='cities.city'),
        ),
    ]
