# Generated by Django 3.1.11 on 2021-06-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0004_auto_20210617_1851'),
        ('trains', '0003_auto_20210617_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название маршрута')),
                ('road_time', models.SmallIntegerField(verbose_name='Общее время в пути')),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from', to='cities.city', verbose_name='Из какого города')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to', to='cities.city', verbose_name='В какой город')),
                ('trains', models.ManyToManyField(to='trains.Train', verbose_name='Список поездов')),
            ],
        ),
    ]
