# Generated by Django 3.1.11 on 2021-06-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='City',
        ),
    ]
