# Generated by Django 3.1.11 on 2021-06-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
